language: node_js
node_js:
  - "lts/*"
before_script:
  - echo $PATH
deploy:
  provider: script
  script: npm run clean && npm run build && npm run chrome:package && webstore upload --file chrome.zip --auto-publish
  on:
    branch: master
    tags: true
