language: node_js
node_js:
  - "lts/*"
before_script:
  - echo $PATH
script: echo "npm test temporarily disabled"
deploy:
  skip_cleanup: true
  provider: script
  script: npm run chrome:release
  on:
    branch: master
    tags: true
