language: node_js
node_js:
  - "lts/*"
before_script:
  - echo $PATH
  - npm install -g react-scripts
deploy:
  provider: script
  script: npm run chrome:release
  on:
    branch: master
    tags: true
