language: node_js
node_js:
  - "lts/*"
before_script:
  - echo $PATH
script: echo "npm test temporarily disabled"
deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master
    tags: true
