language: node_js
node_js:
  - "lts/*"
before_script:
  - echo $PATH
script: echo "npm test temporarily disabled"
deploy:
  provider: script
  script: echo $PATH && which react-scripts && npm run clean && npm run build && npm run chrome:package && webstore upload --file chrome.zip --auto-publish
  on:
    branch: master
    tags: true
